name: Hello World

# trigger
on:
  # leaving this empty means we'll manually dispatch the action
  workflow_dispatch: 

# workflow has one or many jobs
# these are what we do whenthe workflow runs
jobs:
  print-hello-world: # job name
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "hello world!"
    
