name: Pull Request Example

# trigger
on:
  pull_request:
    branches:
      - main
    paths:
      - typescript-project/** #only run when a change in this folder or file
  workflow_dispatch: 

jobs:
  pull-request: # job name
    runs-on: ubuntu-latest

    defaults:
      run:
        # use cron-example as the default working directory
        working-directory: typescript-project

    steps:
      - uses: actions/checkout@v2 

      # setup node
      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: typescript-project/yarn.lock

      # install yarn
      - name: Install yarn
        run: npm install --global yarn

      # install dependencies/ libraries
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # run cucumber tests
      - name: Run Tests
        run: yarn test
