name: Pull Request Example

# trigger
on:
  workflow_dispatch: 

jobs:
  pull-request: # job name
    runs-on: ubuntu-latest

    defaults:
      run:
        # use cron-example as the default working directory
        working-directory: typescript-project

    steps:
      - uses: actions/checkout@v2 

      # setup node
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'npm' # between jobs this will cache our packages for us making installs faster

      # install yarn
      - name: Install yarn
        run: npm install --global yarn

      # install dependencies/ libraries
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build project
        run: yarn build
      # run cucumber tests
      - name: Run Tests
        run: yarn test
