name: Pull Request Example

# trigger
on:
  pull_request:
    branches:
      - main
    paths:
      - typescript-project/** #only run when a change in this folder or file
  workflow_dispatch: 

jobs:
  pull-request: # job name
    runs-on: ubuntu-latest

    defaults:
      run:
        # use cron-example as the default working directory
        working-directory: typescript-project

    steps:
      - uses: actions/checkout@v2 

      # setup node
      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: typescript-project/yarn.lock

      # Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Install libraries
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run linting
      - name: Run linting
        run: yarn lint

      # Compile the code
      - name: Build project
        run: yarn build

      # Run tests
      - name: Run tests
        run: yarn test
